name: Production

# Controls when the workflow will run
on:
  # Triggers the workflow on push only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  prod:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
    - uses: actions/checkout@v2

    - name: Force pull from main
      run: |
        git checkout production
        git reset --hard main

    - name: Remove File
      uses: JesseTG/rm@v1.0.0
      with:
        path: |
          .github
          .gitignore
          *.md

    - name: Auto Minify
      uses: nizarmah/auto-minify@v2.1
      with:
        overwrite: true

    # Auto commits minified content to the existing files
    # Ignore it if you don't want to commit the files to the repository 
    - name: Auto committing minified files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: production
